# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: UX Lift
email: m@kevan.tv
description: > # this means to ignore newlines until "baseurl:"
  On product design, usability and user experience.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.uxlift.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:year/:month/:day/:title/
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  concepts:
    output: true
    permalink: /concepts/:path/
  techniques:
    output: true
    permalink: /techniques/:path/
  resourcearticle:
    output: true
    permalink: /articles/:path/
  books:
    output: true
    permalink: /books/:path/
  resources:
    output: true
    permalink: /resources/:path/
  tools:
    output: true
    permalink: /tools/:path/

defaults:
  -
    scope:
      path: ""
      type: concepts
    values:
      layout: link
      title: ""
      intro: ""
      tags: []
      linkurl: ""
      authors: ""
      year: ""
      type: external-link-alt
  -
    scope:
      path: ""
      type: techniques
    values:
      layout: link
      title: ""
      intro: ""
      tags: []
      linkurl: ""
      authors: ""
      year: ""
      type: external-link-alt
  -
    scope:
      path: ""
      type: resourcearticle
    values:
      layout: article
      title: ""
      intro: ""
      categories: []
  -
    scope:
      path: ""
      type: books
    values:
      title: ""
      tags: []
      booklink: ""
      imprint: ""
      authors: ""
      datepublished: ""
      image: ""
      layout: book
      type: book
  -
    scope:
      path: ""
      type: resources
    values:
      layout: link
      title: ""
      intro: ""
      tags: []
      linkurl: ""
      type: "toolbox"
  -
    scope:
      path: ""
      type: tools
    values:
      layout: link
      image: ""
      title: ""
      intro: ""
      tags: []
      linkurl: ""
      type: "tools"
