---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: directory
  path: _topics
  label: Topics
  create: documents
  match: "**/*"
  templates:
  - topic
- type: directory
  path: _topic-categories
  label: Topic categories
  create: documents
  match: "**/*"
  templates:
  - topic-hub
- type: directory
  path: _publications
  label: Publications
  create: documents
  match: "**/*"
- type: directory
  path: _design-systems
  label: Design systems
  create: documents
  match: "**/*"
  templates:
  - design-system
- type: directory
  path: _tools
  label: Tools
  create: documents
  match: "**/*"
  templates:
  - tool
- type: directory
  path: _tool-categories
  label: Tool categories
  create: documents
  match: "**/*"
- type: directory
  path: _plugin
  label: Plugins
  create: documents
  match: "**/*"
  templates:
  - plugin
- type: directory
  path: _books
  label: Books
  create: documents
  match: "**/*"
  templates:
  - book
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: _data
  label: Data
  create: all
  match: "**/*"
upload_dir: assets/images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
instant_preview: false
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
