# config.yml

backend:
  name: github
  repo: MattKevan/uxlift
  branch: master # Branch to update (optional; defaults to master)
  open_authoring: true
media_folder: 'assets/images'
show_preview_links: false
publish_mode: editorial_workflow
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }
  - name: 'topics'
    label: 'Topic'
    folder: '_topics/'
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Link", name: "link", widget: "string"}
      - label: "Organisation"
        name: "organisation"
        widget: "relation"
        collection: "organisations"
        search_fields: ["title"]
        value_field: "title"
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "people"
        search_fields: ["title"]
        value_field: "title"
      - label: "Categories"
        name: "category"
        widget: "relation"
        collection: "topic-categories"
        search_fields: ["title"]
        value_field: "title"
        multiple: true
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: 'organisations'
    label: 'Organisation'
    folder: '_organisations/'
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Image"
        name: "image"
        widget: "image"
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Link", name: "link", widget: "string"}
      - label: "Organisation type"
        name: "org-type"
        widget: "relation"
        collection: "organisation-type"
        search_fields: ["title"]
        value_field: "title"
      - label: "Categories"
        name: "category"
        widget: "relation"
        collection: "topic-categories"
        search_fields: ["title"]
        value_field: "title"
        multiple: true
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: 'tool'
    label: 'Tool'
    folder: '_tools/'
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Image"
        name: "image"
        widget: "image"
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Link", name: "link", widget: "string"}
      - label: "Organisation"
        name: "organisations"
        widget: "relation"
        collection: "organisations"
        search_fields: ["title"]
        value_field: "title"
      - label: "Categories"
        name: "category"
        widget: "relation"
        collection: "topic-categories"
        search_fields: ["title"]
        value_field: "title"
        multiple: true
      - {label: "Body", name: "body", widget: "markdown", required: false}     

