# config.yml

backend:
  name: github
  repo: MattKevan/uxlift
  branch: master # Branch to update (optional; defaults to master)
  open_authoring: true
media_folder: 'assets/images'
show_preview_links: false
publish_mode: editorial_workflow
collections:

# Topics

  - name: 'topics'
    label: 'Topics'
    folder: '_topics/'
    create: true
    editor:
      preview: false
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Link", name: "link", widget: "string"}
      - label: "Organisation"
        name: "organisation"
        widget: "relation"
        collection: "organisations"
        search_fields: ["title"]
        value_field: "title"
        required: false
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "people"
        search_fields: ["title"]
        value_field: "title"
        required: false
      - label: "Team"
        name: "team"
        widget: "relation"
        collection: "teams"
        search_fields: ["title"]
        value_field: "title"
        required: false
      - label: "Categories"
        name: "category"
        widget: "relation"
        collection: "topic-categories"
        search_fields: ["title"]
        value_field: "title"
        multiple: true
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: 'topic-categories'
    label: 'Topic categories'
    folder: '_topic-categories/'
    create: true
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}

# Resources

  - name: 'resources'
    label: 'Resources'
    folder: '_resources/'
    create: true
    editor:
      preview: false
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Link", name: "link", widget: "string"}
      - label: "Organisation"
        name: "organisation"
        widget: "relation"
        collection: "organisations"
        search_fields: ["title"]
        value_field: "title"
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "people"
        search_fields: ["title"]
        value_field: "title"
      - label: "Team"
        name: "team"
        widget: "relation"
        collection: "teams"
        search_fields: ["title"]
        value_field: "title"
      - label: "Categories"
        name: "category"
        widget: "relation"
        collection: "topic-categories"
        search_fields: ["title"]
        value_field: "title"
        multiple: true
      - label: "Resource type"
        name: "resource-type"
        widget: "relation"
        collection: "resource-types"
        search_fields: ["title"]
        value_field: "title"
        multiple: true
      - {label: "Body", name: "body", widget: "markdown", required: false}  

  - name: 'resource-types'
    label: 'Resource type'
    folder: '_resource-types/'
    create: true
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Short title", name: "short-title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}

# Tools

  - name: 'tools'
    label: 'Tools'
    folder: '_tools/'
    create: true
    editor:
      preview: false
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Link", name: "link", widget: "string"}
      - label: "Organisation"
        name: "organisations"
        widget: "relation"
        collection: "organisations"
        search_fields: ["title"]
        value_field: "title"
      - label: "Topic categories"
        name: "category"
        widget: "relation"
        collection: "topic-categories"
        search_fields: ["title"]
        value_field: "title"
        multiple: true
      - label: "Tool categories"
        name: "tool-category"
        widget: "relation"
        collection: "tool-categories"
        search_fields: ["title"]
        value_field: "title"
        multiple: true
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: 'tool-categories'
    label: 'Tool categories'
    folder: '_tool-categories/'
    create: true
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}

# Books

# Design systems

# Organisations

  - name: 'organisations'
    label: 'Organisations'
    folder: '_organisations/'
    create: true
    editor:
      preview: false
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Link", name: "link", widget: "string"}
      - label: "Organisation type"
        name: "org-type"
        widget: "relation"
        collection: "organisation-types"
        search_fields: ["title"]
        value_field: "title"
      - label: "Categories"
        name: "category"
        widget: "relation"
        collection: "topic-categories"
        search_fields: ["title"]
        value_field: "title"
        multiple: true
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: 'org-type'
    label: 'Organisation type'
    folder: '_organisation-types/'
    create: true
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Short title", name: "short-title", widget: "string"}
      - {label: "Description", name: "description", widget: "text" }

# Courses

  - name: 'course-types'
    label: 'Course types'
    folder: '_course-types/'
    create: true
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Short title", name: "short-title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}

# People

  - name: 'people'
    label: 'People'
    folder: '_people/'
    create: true
    editor:
      preview: false
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", required: false}

# Teams

  - name: 'teams'
    label: 'Teams'
    folder: '_teams/'
    create: true
    editor:
      preview: false
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", required: false}




 