# config.yml

backend:
  name: github
  repo: MattKevan/uxlift
  branch: master # Branch to update (optional; defaults to master)
  open_authoring: true
media_folder: 'assets/images'
show_preview_links: false
publish_mode: editorial_workflow
collections:
  - name: 'topics'
    label: 'Topic'
    folder: '_topics/'
    create: true
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Link", name: "link", widget: "string"}
      - label: "Organisation"
        name: "organisation"
        widget: "relation"
        collection: "organisations"
        search_fields: ["title"]
        value_field: "title"
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "people"
        search_fields: ["title"]
        value_field: "title"
      - label: "Categories"
        name: "category"
        widget: "relation"
        collection: "topic-categories"
        search_fields: ["title"]
        value_field: "title"
        multiple: true
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: 'organisations'
    label: 'Organisation'
    folder: '_organisations/'
    create: true
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Image"
        name: "image"
        widget: "image"
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Link", name: "link", widget: "string"}
      - label: "Organisation type"
        name: "org-type"
        widget: "relation"
        collection: "organisation-type"
        search_fields: ["title"]
        value_field: "title"
      - label: "Categories"
        name: "category"
        widget: "relation"
        collection: "topic-categories"
        search_fields: ["title"]
        value_field: "title"
        multiple: true
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: 'tool'
    label: 'Tool'
    folder: '_tools/'
    create: true
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Image"
        name: "image"
        widget: "image"
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Link", name: "link", widget: "string"}
      - label: "Organisation"
        name: "organisations"
        widget: "relation"
        collection: "organisations"
        search_fields: ["title"]
        value_field: "title"
      - label: "Categories"
        name: "category"
        widget: "relation"
        collection: "topic-categories"
        search_fields: ["title"]
        value_field: "title"
        multiple: true
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: 'resource'
    label: 'Resource'
    folder: '_resource/'
    create: true
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Link", name: "link", widget: "string"}
      - label: "Organisation"
        name: "organisation"
        widget: "relation"
        collection: "organisations"
        search_fields: ["title"]
        value_field: "title"
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "people"
        search_fields: ["title"]
        value_field: "title"
      - label: "Categories"
        name: "category"
        widget: "relation"
        collection: "topic-categories"
        search_fields: ["title"]
        value_field: "title"
        multiple: true
      - {label: "Body", name: "body", widget: "markdown", required: false}  
  - name: 'org-type'
    label: 'Organisation type'
    folder: '_organisation-types/'
    create: true
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Short title", name: "short-title", widget: "string"}
      - {label: "Description", name: "description", widget: "text" }
  - name: 'resource-type'
    label: 'Resource type'
    folder: '_resource-types/'
    create: true
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Short title", name: "short-title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
  - name: 'resource-type'
    label: 'Resource type'
    folder: '_resource-types/'
    create: true
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Short title", name: "short-title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
  - name: 'course-type'
    label: 'Course type'
    folder: '_course-types/'
    create: true
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Short title", name: "short-title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
  - name: 'categories'
    label: 'Categories'
    folder: '_topic-categories/'
    create: true
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}