---
label: Plugin
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
- type: text
  name: link
  label: link
- type: list
  name: category
  label: category
- type: file
  name: image
  label: image
- type: list
  name: tool
  label: tool
pages:
- _plugin/sketch-cluse.md
